services:
  postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    healthcheck:
      test: [CMD-SHELL, pg_isready, --dbname=postgres, --username=postgres]
    restart: on-failure:3

volumes:
  postgres_data:
