name: Push to frontend

on:
  push:
    branches:
      - master
    paths-ignore:
      - './kubernetes/**'
      - './src/**'
      - './test/**'

  workflow_dispatch:

jobs:
  deploy-frontend:
    uses: ./.github/workflows/_deploy-frontend.yml
    secrets:
      AWS_CDK_DEPLOY_ROLE_ARN: ${{ secrets.AWS_CDK_DEPLOY_ROLE_ARN }}
    permissions:
      id-token: write
      contents: read
